# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'



- script: |
    wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
    chmod +x codeql-runner-linux
  displayName: 'Get latest CodeQL package. Install on Agent.'

- script: |
    ./codeql-runner-linux init \
    --repository fypjsecuredevops2021/vulnerable-node \
    --github-url https://github.com \
    --github-auth $(GitHub Token) \
     displayName: 'Initialize CodeQL Executable and create a CodeQL database'

- script: |
    ./codeql-runner-linux analyze \
    --repository fypjsecuredevops2021/vulnerable-node \
    --github-url https://github.com \
    --github-auth $(GitHub Token) \
    --commit $(Build.SourceVersion) \
    --ref $(Build.SourceBranch)
  displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'